#server:
#  port: ${random.int(7000,7900)}
server:
  port: 7801
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: service-provider
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.qq.cloud: DEBUG
eureka:
  client:
    service-url:
#      defaultZone: http://pengpeng:password1@localhost:9800/eureka/  # user a eureka service discovery server
       defaultZone: http://localhost:7801/eureka/, http://localhost:9801/eureka/
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
    hostname: localhost
    prefer-ip-address: true
